#!/usr/bin/bash

# Runs an errai build repeatedly until failure.
# Good for finding hiesenbugs.

if [ $# -ne 1 ]; then
  echo "usage: $0 {num_times}" >&2
  exit 1
fi

OUTPUT_DIR="output"
mkdir $OUTPUT_DIR

i=$1
while [ $i -gt 0 ]; do
  echo "Starting build ${i}..."
  success=0
  mvn clean package  -Dgwt.extraJvmArgs="-Derrai.codegen.permissive=true" > "$OUTPUT_DIR/stdout" 2> "$OUTPUT_DIR/stderr" && success=1

  if [ $success -eq 0 ]; then
    echo "Build failed. Copying .errai/ contents..."
    cp -r .errai/* $OUTPUT_DIR
    exit 0
  fi

  rm "$OUTPUT_DIR/stdout"
  rm "$OUTPUT_DIR/stderr"

  i=`expr $i - 1`
done

exit 0
