#!/usr/bin/bash

dir="`pwd`"
delete=0
if [ $# -eq 1 ]
then
	dir="`echo $1 | sed s:/$::`"
elif [ $# -eq 2 -a "$1" = "-d" ]
then
	dir="`echo $2 | sed s:/$::`"
	delete=1
else
	echo "usage: $0 [-d] dir" > 2
fi


for f in $dir/*.java
do
	pdir="`grep -m 1 package "$f" | sed s:package::1 | tr -d ';' | tr '.' '/' | tr -d ' '`"
	mkdir -p "$dir/$pdir"
	echo "Directory made: '${dir}/${pdir}'"
	cp "$f" "$dir/$pdir/"
	echo "$f copied to '${dir}/${pdir}'"
	if [ $delete -eq 1 ]
	then
		rm -f "$f"
		echo "deleted $f"
	fi
done
