#!/usr/bin/bash

# Runs an errai build repeatedly until failure.
# Good for finding hiesenbugs.

# Process opts
GOALS=""
while [ $# -gt 1 ]; do
  GOALS="$GOALS $1"
  shift
done

if [ $# -ne 1 ]; then
  echo "usage: $0 {mvn goals...} {num_times}" >&2
  exit 1
fi

OUTPUT_DIR="output"
mkdir $OUTPUT_DIR

TOTAL=$1
i=1
while [ $i -le $TOTAL ]; do
  echo
  echo ---------------------------------
  echo Starting build $i
  echo ---------------------------------
  echo

  mvn $GOALS 2>&1 | tee "$OUTPUT_DIR/out"
  result=${PIPESTATUS[0]}

  if [ $result -eq 1 ]; then
    echo
    echo ---------------------------------
    echo Build $i failed. Exiting.
    echo ---------------------------------
    echo
    exit 0
  fi

  i=`expr $i + 1`
done

exit 0
